name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test-general:
    name: 'Test Package'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master
      - name: 'Start JupyterHub'
        working-directory: tests/assets
        run: |
          docker-compose up --build -d
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -v
        env:
          JUPYTERHUB_API_TOKEN: GiJ96ujfLpPsq7oatW1IJuER01FbZsgyCM0xH6oMZXDAV6zUZsFy3xQBZakSBo6P
      - name: Run command line
        run: |
          python -m jupyterhub_client run --temporary-user -n tests/assets/notebook/simple.ipynb
        env:
          JUPYTERHUB_API_TOKEN: GiJ96ujfLpPsq7oatW1IJuER01FbZsgyCM0xH6oMZXDAV6zUZsFy3xQBZakSBo6P
